import type { GameData, EntityData } from "./engine.js";

/**
 * Protoss game data.
 *
 * ┌───────────────────────────────────────────────────────────────────────┐
 * │  Costs, supply, and build times below are taken from SC2's OWN game     │
 * │  data (the data.json generated by BurnySc2/sc2-techtree, the same file  │
 * │  BuRny's planner uses). That snapshot is current to patch 5.0.16         │
 * │  (verified: it already carries Nexus supply = 13, the 5.0.16 value).    │
 * │                                                                         │
 * │  TIME UNIT: build times are in FASTER-clock seconds — the value the     │
 * │  in-game timer shows and that build orders quote. The raw game data     │
 * │  stores Normal-speed seconds; Faster = raw / 1.4 (Probe 17 -> 12.1).    │
 * │  Verified against known values: Probe 12, Gateway 46, Nexus 71. Income  │
 * │  rates use the same Faster clock.                                        │
 * │                                                                         │
 * │  Confirmed 5.0.16 economy overrides: startingWorkers 12->8, Nexus       │
 * │  supply 15->13. Chrono Boost: 50 energy, +50% for 20s; Nexus starts     │
 * │  50 energy, 200 max, regen 0.5625/s.                                     │
 * │                                                                         │
 * │  ⚠️ Still calibration targets (NOT in the game data — they come from     │
 * │  mining behavior): mineralRate*, gasRatePerWorker, probeBuildOccupancy.  │
 * │  Tune these against headless SC2 (see README "Validation").              │
 * └───────────────────────────────────────────────────────────────────────┘
 */

function ent(
  name: string,
  minerals: number,
  gas: number,
  buildTime: number,
  producer: string,
  opts: Partial<EntityData> = {},
): EntityData {
  return {
    name,
    minerals,
    gas,
    buildTime,
    producer,
    supplyCost: opts.supplyCost ?? 0,
    supplyProvided: opts.supplyProvided ?? 0,
    requires: opts.requires ?? [],
    isStructure: opts.isStructure ?? false,
  };
}

const entities: Record<string, EntityData> = {};
function add(e: EntityData) {
  entities[e.name] = e;
}

// Build times are Faster-clock seconds (raw game data / 1.4). See header.
// --- Structures ---------------------------------------------------------
add(ent("Nexus", 400, 0, 71.4, "Probe", { supplyProvided: 13, isStructure: true }));
add(ent("Pylon", 100, 0, 17.9, "Probe", { supplyProvided: 8, isStructure: true }));
add(ent("Assimilator", 75, 0, 21.4, "Probe", { isStructure: true }));
add(ent("Gateway", 150, 0, 46.4, "Probe", { isStructure: true, requires: ["Pylon"] }));
add(ent("CyberneticsCore", 150, 0, 35.7, "Probe", { isStructure: true, requires: ["Gateway"] }));
add(ent("Forge", 150, 0, 32.1, "Probe", { isStructure: true, requires: ["Pylon"] }));
add(ent("TwilightCouncil", 150, 100, 35.7, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));
add(ent("Stargate", 150, 150, 42.9, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));
add(ent("RoboticsFacility", 150, 100, 46.4, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));

// --- Nexus-produced -----------------------------------------------------
add(ent("Probe", 50, 0, 12.1, "Nexus", { supplyCost: 1 }));

// --- Gateway units ------------------------------------------------------
add(ent("Zealot", 100, 0, 27.1, "Gateway", { supplyCost: 2 }));
add(ent("Stalker", 125, 50, 27.1, "Gateway", { supplyCost: 2, requires: ["CyberneticsCore"] }));
add(ent("Adept", 100, 25, 32.5, "Gateway", { supplyCost: 2, requires: ["CyberneticsCore"] }));
add(ent("Sentry", 50, 100, 23.3, "Gateway", { supplyCost: 2, requires: ["CyberneticsCore"] }));

// --- Stargate units -----------------------------------------------------
add(ent("Oracle", 150, 150, 37.1, "Stargate", { supplyCost: 3 }));
add(ent("VoidRay", 250, 150, 43.0, "Stargate", { supplyCost: 4 }));

// --- Robotics units -----------------------------------------------------
add(ent("Immortal", 250, 100, 39.3, "RoboticsFacility", { supplyCost: 4 }));
add(ent("Observer", 25, 75, 17.9, "RoboticsFacility", { supplyCost: 1 }));

export const PROTOSS: GameData = {
  patch: "5.0.16",
  race: "Protoss",
  economy: {
    startingWorkers: 8, // 5.0.16: was 12
    startingMinerals: 50,
    startingGas: 0,
    mineralPatchesPerBase: 8,
    gasGeysersPerBase: 2,

    // Income calibration targets (resources/second per worker):
    mineralRateFirstWorker: 0.933, // ~56/min, 1st worker on a patch
    mineralRateSecondWorker: 0.7, // ~42/min, 2nd worker on a patch
    gasRatePerWorker: 0.63, // ~38/min, up to 3 per assimilator

    // Chrono Boost / Nexus energy (confirmed LotV):
    nexusStartEnergy: 50,
    nexusMaxEnergy: 200,
    nexusEnergyRegen: 0.5625,
    chronoCost: 50,
    chronoBoostWindow: 20,
    chronoSpeedMultiplier: 1.5,

    probeBuildOccupancy: 4, // seconds a probe is off minerals to start a structure
  },
  entities,
};
