import type { GameData, EntityData } from "./engine.js";

/**
 * Protoss game data.
 *
 * ┌───────────────────────────────────────────────────────────────────────┐
 * │  Costs, supply, and build times below are taken from SC2's OWN game     │
 * │  data (the data.json generated by BurnySc2/sc2-techtree, the same file  │
 * │  BuRny's planner uses). That snapshot is current to patch 5.0.16         │
 * │  (verified: it already carries Nexus supply = 13, the 5.0.16 value).    │
 * │                                                                         │
 * │  TIME UNIT: build times are in FASTER-clock seconds — the value the     │
 * │  in-game timer shows and that build orders quote. The raw game data     │
 * │  stores Normal-speed seconds; Faster = raw / 1.4 (Probe 17 -> 12.1).    │
 * │  Verified against known values: Probe 12, Gateway 46, Nexus 71. Income  │
 * │  rates use the same Faster clock.                                        │
 * │                                                                         │
 * │  Confirmed 5.0.16 economy overrides: startingWorkers 12->8, Nexus       │
 * │  supply 15->13. Chrono Boost: 50 energy, +50% for 20s; Nexus starts     │
 * │  50 energy, 200 max, regen 0.5625/s.                                     │
 * │                                                                         │
 * │  ⚠️ Still a calibration target (NOT in the game data — comes from        │
 * │  mining behavior, hard to isolate from replay bank data alone):          │
 * │  probeBuildOccupancy. mineralRate* and gasRatePerWorker are now fit      │
 * │  directly from replay income data — see the economy block below.        │
 * └───────────────────────────────────────────────────────────────────────┘
 */

function ent(
  name: string,
  minerals: number,
  gas: number,
  buildTime: number,
  producer: string,
  opts: Partial<EntityData> = {},
): EntityData {
  // Defaults first, then spread opts so ALL optional fields (moveSpeed,
  // morphFrom, isUpgrade, warpCooldown, isWorker, ...) carry through.
  return {
    name,
    minerals,
    gas,
    buildTime,
    producer,
    supplyCost: 0,
    supplyProvided: 0,
    requires: [],
    isStructure: false,
    ...opts,
  };
}

const entities: Record<string, EntityData> = {};
function add(e: EntityData) {
  entities[e.name] = e;
}

// Build times are Faster-clock seconds (raw game data / 1.4). See header.
// --- Structures ---------------------------------------------------------
add(ent("Nexus", 400, 0, 71.4, "Probe", { supplyProvided: 13, isStructure: true, isTownhall: true }));
add(ent("Pylon", 100, 0, 17.9, "Probe", { supplyProvided: 8, isStructure: true }));
add(ent("Assimilator", 75, 0, 21.4, "Probe", { isStructure: true }));
add(ent("Gateway", 150, 0, 46.4, "Probe", { isStructure: true, requires: ["Pylon"] }));
add(ent("CyberneticsCore", 150, 0, 35.7, "Probe", { isStructure: true, requires: ["Gateway"] }));
add(ent("Forge", 150, 0, 32.1, "Probe", { isStructure: true, requires: ["Pylon"] }));
add(ent("TwilightCouncil", 150, 100, 35.7, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));
add(ent("Stargate", 150, 150, 42.9, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));
add(ent("RoboticsFacility", 150, 100, 46.4, "Probe", { isStructure: true, requires: ["CyberneticsCore"] }));
// Roster expansion (Scouting Report Phase 3, 2026-07-06) -- costs/times
// verified against Liquipedia's LotV pages (converted Normal -> Faster / 1.4,
// same convention as every other structure above), not replay-verified.
add(ent("TemplarArchives", 150, 200, 25.7, "Probe", { isStructure: true, requires: ["TwilightCouncil"] }));
add(ent("DarkShrine", 150, 150, 50.7, "Probe", { isStructure: true, requires: ["TwilightCouncil"] }));
add(ent("RoboticsBay", 150, 150, 32.9, "Probe", { isStructure: true, requires: ["RoboticsFacility"] }));

// --- Warp Gate tech ------------------------------------------------------
// Warp Gate research is at the Cybernetics Core (the 5.0.16 PTR briefly moved it
// to the Gateway; that was reverted in the live hotfixes). A Warp Gate is a
// Gateway morphed in place (~7s). Once you have Warp Gates and a powered Pylon,
// you WARP units in there (~4s) — planting a proxy Pylon near the enemy delivers
// the army at the front instead of walking it across the map.
add(ent("WarpGateResearch", 50, 50, 100, "CyberneticsCore", { isUpgrade: true, requires: ["CyberneticsCore"] }));
add(ent("WarpGate", 25, 25, 7, "Gateway", { isStructure: true, morphFrom: "Gateway", requires: ["WarpGateResearch"] }));

// --- Combat upgrades (Scouting Report Phase 2, 2026-07-06) ---------------
// Costs/times are well-known LotV-stable book values (100/100, 113s Normal
// for Forge tiers; 100/100 & 150/150 for Charge/Blink), same "book value,
// not independently verified" status as this file's baseline combat stats.
// See EntityData.upgrades for how the dps/ehp multipliers below are derived
// and applied -- this model only has aggregate dps/hp, not per-hit damage,
// so each multiplier is computed from that unit's known real per-hit
// damage (shown beside each entry) rather than measured directly.
add(ent("GroundWeaponsLevel1", 100, 100, 80.7, "Forge", { isUpgrade: true, requires: ["Forge"] }));
add(ent("GroundArmorLevel1", 100, 100, 80.7, "Forge", { isUpgrade: true, requires: ["Forge"] }));
// Charge has no literal weapon-file change in the real game -- its value is
// entirely positioning (closing gaps, staying on top of kiting targets),
// which this engine doesn't model. The dpsMultiplier below is an explicit,
// documented stand-in for "less time spent not-attacking," not a measured
// combat-log effect.
add(ent("Charge", 100, 100, 35.7, "TwilightCouncil", { isUpgrade: true, requires: ["TwilightCouncil"] }));
// Same caveat as Charge: Blink's real value is disengaging bad trades, which
// this engine's combat resolver has no concept of. The ehpMultiplier below
// stands in for "fewer Stalkers actually die because they blinked out."
add(ent("Blink", 150, 150, 71.4, "TwilightCouncil", { isUpgrade: true, requires: ["TwilightCouncil"] }));

// --- Nexus-produced -----------------------------------------------------
add(ent("Probe", 50, 0, 12.1, "Nexus", { supplyCost: 1, isWorker: true, moveSpeed: 2.8125 }));

// --- Gateway units (warpCooldown ~ build time - 7s, per Liquipedia) -------
// Adept pre-warpgate build time bumped 30 -> 33 by the 5.0.16 hotfix.
//
// ⚠️ dps/hp/shields below are standard baseline (NO upgrades, no bonus-vs-
// armor/light) LotV-era figures, for ranking builds by unitValue() — NOT
// verified against 5.0.16 game data the way cost/buildTime are. Combat
// abilities (Blink, Guardian Shield, Pulsar Beam ramp, ...) are not
// modeled at all yet; dps is the raw autoattack only.
// upgrades: dpsMultiplier for GroundWeaponsLevel1 is (baseDmg+1)/baseDmg per
// hit instance (Zealot's dual 8+8 blades each get +1: 18/16; Stalker's single
// 13-dmg hit: 14/13; Adept's 10-dmg hit: 11/10; Sentry's 6-dmg hit: 7/6).
// ehpMultiplier for GroundArmorLevel1 is a flat +5% stand-in for "+1 armor"
// (this model has no per-hit granularity to convert armor exactly).
add(ent("Zealot", 100, 0, 27.1, "Gateway", {
  supplyCost: 2, moveSpeed: 2.25, warpCooldown: 20, dps: 18.6, hp: 100, shields: 50,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 18 / 16 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
    { name: "Charge", dpsMultiplier: 1.15 },
  ],
}));
add(ent("Stalker", 125, 50, 27.1, "Gateway", {
  supplyCost: 2, moveSpeed: 2.9531, warpCooldown: 20, requires: ["CyberneticsCore"], dps: 9.7, hp: 100, shields: 80,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 14 / 13 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
    { name: "Blink", ehpMultiplier: 1.10 },
  ],
}));
add(ent("Adept", 100, 25, 33.0, "Gateway", {
  supplyCost: 2, moveSpeed: 2.5, warpCooldown: 26, requires: ["CyberneticsCore"], dps: 6.2, hp: 70, shields: 70,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 11 / 10 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));
add(ent("Sentry", 50, 100, 23.3, "Gateway", {
  supplyCost: 2, moveSpeed: 2.5, warpCooldown: 20.3, requires: ["CyberneticsCore"], dps: 8.4, hp: 40, shields: 40,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 7 / 6 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));

// --- Templar Archives / Dark Shrine units (Phase 3 roster expansion) -----
// High Templar's Psionic Storm and Feedback are NOT modeled (this project's
// established "no special abilities" convention, same as Sentry's Force
// Field) -- dps below is its raw Psi Blast autoattack only, which real
// players rarely rely on. Dark Templar's permanent cloak (its actual
// gameplay value) is likewise unrepresentable here; dps is its autoattack.
add(ent("HighTemplar", 50, 150, 30.7, "Gateway", {
  supplyCost: 2, moveSpeed: 2.82, warpCooldown: 23.7, requires: ["TemplarArchives"], dps: 3.2, hp: 40, shields: 40,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 5 / 4 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));
add(ent("DarkTemplar", 125, 125, 30.7, "Gateway", {
  supplyCost: 2, moveSpeed: 3.94, warpCooldown: 23.7, requires: ["DarkShrine"], dps: 37.2, hp: 40, shields: 80,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 46 / 45 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));
// Archon: a real merge of TWO Templars in the field, not built at any
// building -- this engine's morphFrom only supports consuming ONE unit of
// the source type, so this models the cheapest real path (2 High Templar,
// 100/300 combined) as morphFrom "HighTemplar" with the Archon's OWN cost
// set to the DELTA beyond one already-built High Templar (50/150, since the
// 1st HT's 50/150 was already paid when it was trained) -- a build order
// still writes "HighTemplar, HighTemplar, Archon" and totals the correct
// 100/300 combined cost. Documented limitation: the engine only decrements
// ONE HighTemplar on this morph (see State's morph-completion branch), so
// nothing stops a build from merging after just 1 High Templar instead of 2 --
// not silently wrong, just an engine-model ceiling shared with every other
// morphFrom relationship here. Real merge/Dark Templar combos (250/250 or
// 175/275) aren't representable at all under a single morphFrom source.
add(ent("Archon", 50, 150, 6.1, "HighTemplar", {
  supplyCost: 2, moveSpeed: 3.94, morphFrom: "HighTemplar", dps: 20.0, hp: 10, shields: 350,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 26 / 25 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));

// --- Stargate units -----------------------------------------------------
// No Air Weapons/Armor upgrade modeled yet (out of scope this pass, see
// README roadmap) -- Stargate units get no upgrades entry.
add(ent("Oracle", 150, 150, 37.1, "Stargate", { supplyCost: 3, moveSpeed: 4.0, dps: 16.7, hp: 100, shields: 60 }));
add(ent("VoidRay", 250, 150, 43.0, "Stargate", { supplyCost: 4, moveSpeed: 2.75, dps: 16.8, hp: 150, shields: 100 }));

// --- Robotics units -----------------------------------------------------
// Immortal's attack fires two 20-dmg hits per cycle; +1 applies to each: 42/40.
add(ent("Immortal", 250, 100, 39.3, "RoboticsFacility", {
  supplyCost: 4, moveSpeed: 2.25, dps: 19.2, hp: 200, shields: 100,
  upgrades: [
    { name: "GroundWeaponsLevel1", dpsMultiplier: 42 / 40 },
    { name: "GroundArmorLevel1", ehpMultiplier: 1.05 },
  ],
}));
// Observer has no weapon (pure scout/detector) — dps 0, contributes no
// fighting VALUE by design, even though it has real strategic value.
add(ent("Observer", 25, 75, 17.9, "RoboticsFacility", { supplyCost: 1, moveSpeed: 2.0156, hp: 40, shields: 20 }));
// Colossus's Thermal Lance is actually upgraded by Protoss AIR Weapons (a
// real-game quirk despite Colossus being ground-only) -- out of scope this
// pass (no Air Weapons upgrade modeled, see Stargate units above), so only
// Ground Armor applies here, not a weapon multiplier. Splash/bonus-vs-light
// not modeled (this project's usual simplification).
add(ent("Colossus", 300, 200, 38.6, "RoboticsFacility", {
  supplyCost: 6, moveSpeed: 3.15, requires: ["RoboticsBay"], dps: 18.7, hp: 250, shields: 100,
  upgrades: [{ name: "GroundArmorLevel1", ehpMultiplier: 1.05 }],
}));
// Disruptor has no autoattack (Purification Nova is an activated ability,
// this project's usual "no special abilities" convention) -- dps 0,
// contributes no fighting VALUE by this ranking signal, same treatment as
// Observer/Medivac, even though its real combat value is entirely ability-based.
add(ent("Disruptor", 150, 150, 25.7, "RoboticsFacility", { supplyCost: 4, moveSpeed: 3.15, requires: ["RoboticsBay"], hp: 100, shields: 100 }));

export const PROTOSS: GameData = {
  patch: "5.0.16",
  race: "Protoss",
  economy: {
    startingWorkers: 8, // 5.0.16: was 12
    startingMinerals: 50,
    startingGas: 0,
    mineralPatchesPerBase: 8,
    gasGeysersPerBase: 2,
    startingTownhall: "Nexus",
    gasStructure: "Assimilator",
    supplyStructure: "Pylon",
    hasChrono: true,
    hasWarpGate: true,

    // Mineral rates (min/sec per worker), FIT DIRECTLY from replay income data
    // via tools/calibrate_income.py: a tiered (rate1==rate2, distinct rate3)
    // ordinary-least-squares fit against every steady-state PlayerStatsEvent
    // sample (t <= 240s, >=25s after the last Assimilator/Nexus change).
    //   Corpus EXPANDED 2026-07-05: added Protoss-side data from 2 more real
    //   5.0.16 games (llllllllllll in SortOf_vs_llllllllllll_ZvP, ByuN's
    //   opponent UEDdemonFan) on top of the original 3, for 103 mineral / 58
    //   gas samples across 5 independent replays. R² = 0.917 mineral, 0.900
    //   gas — both essentially unchanged from the first-pass fit (0.871/0.652
    //   mineral, 0.871 gas), which is itself a good sign: more data didn't
    //   move the estimate, so the original 3-replay fit wasn't a fluke.
    //   ⚠️ Known open tension: npm run validate's two hand-transcribed Spawning
    //   Tool builds now show MORE deviation than before (1.9s/7.8s MAE -> 4.3s/
    //   12.9s), because 0.925 had been tuned to fit those exact two milestone
    //   lists directly (see git history) — good for those two games, but only
    //   2 data points, and circular as a calibration target. This fit instead
    //   regresses directly against real income samples across independent
    //   replays, which is less overfit-prone even though it now tracks those
    //   two specific published builds a bit less tightly (plausibly because
    //   those two games individually had cleaner-than-average probe micro).
    mineralRateFirstWorker: 0.871, // ~52.3/min
    mineralRateSecondWorker: 0.871, // ~52.3/min (equal to 1st; fit assumes this per the treatise's structure)
    mineralRateThirdWorker: 0.61, // ~36.6/min — oversaturated workers mine far closer to full rate than
    // the old 0.33 guess assumed (0.61/0.871 ≈ 70%, not ~36%); 58 real samples now exercise this tier
    // (up from 23), landing a bit lower than the first pass's 0.652 but same ballpark.
    miningMicro: 1.0, // 1.0 = the replay-fit average pro game above; ~0.9 for scrappier a-move ladder play
    // Gas: single-tier fit (no oversaturation concept — gas workers cap at 3/geyser),
    // same replays/methodology as above. R² = 0.900. This is a big correction:
    // the old 0.63/s guess was ~38% too low — real gas income is nearly on par
    // with mineral income per worker, not the historically-slower-gas folk model.
    gasRatePerWorker: 0.870, // ~52.2/min; was 0.63 (~38/min)

    // Chrono Boost / Nexus energy (confirmed LotV):
    nexusStartEnergy: 50,
    nexusMaxEnergy: 200,
    nexusEnergyRegen: 0.5625,
    chronoCost: 50,
    chronoBoostWindow: 20,
    chronoSpeedMultiplier: 1.5,

    probeBuildOccupancy: 4, // seconds a probe is off minerals to start a structure
    warpInTime: 4, // 5.0.16 standardized warp-in (old 11.4s proxy penalty removed)
  },
  entities,
};
